// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhksmiryxulaotegdfvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa3NtaXJ5eHVsYW90ZWdkZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzM5OTksImV4cCI6MjA2NTUwOTk5OX0.Syx0TX0hRubH7enPkBmV9gGobiqbBX4f66m_YNLHFLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);